<?php

use Symfony\Component\HttpFoundation\RedirectResponse;


function custom_form_cancelar(){

  //$this->messenger()->addStatus($this->t('Operación cancelada'));
  Drupal::messenger()->addError(t('Canceled process!!!'));      

  global $base_url;
  //dpm($base_url);
  $response = new RedirectResponse($base_url.'/form-example/');
  $response->send();
  return;
}

/**
 * Implements hook_theme().
 */
function my_form_theme($existing, $type, $theme, $path) {
  return [
    'my_form_template' => [
      'variables' => ['test_var' => NULL],
    ],
  ];
}
